### PR TITLE
Fix leaks

### PR DESCRIPTION
**Pull request by mmalecki**
@indexzero can you still reproduce leaks with this branch? These are all the leaks `leaks` tool reported.

### CODE REVIEW

**Comment by indexzero** [comment]
@mmalecki Awesome. @jcrugzz can you take a look at this when you're before you go to Philly?

**Comment by jcrugzz** [comment]
@indexzero yea ill check this out today.

**Comment by jcrugzz** [comment]
@mmalecki Im getting a seg fault running the command found below locally. Im connecting to a standard TCP server at localhost:3001 that logs to the console. It seems to have to do with writing the `start.log` file. Also did you take a look at @Southern's d0d2aae083c60488351bfcb56b212c2944fe3d04 commit? I'm a bit rusty on my C but this seems sane since `saneopt` only malloc's the `opt` var. 

``` bash
/forza -h localhost -p 3001 -- test/fixtures/listen-0.js
forza 0.2.2
connecting to 127.0.0.1:3001...
connected.
uv_write: bad file descriptor
forza(93873,0x7fff716af180) malloc: *** error for object 0x7fff5893c92b: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    93873 abort      ./forza -h localhost -p 3001 -- test/fixtures/listen-0.js
```

**Comment by jcrugzz** [comment]
The current master has the same `uv_write: bad file descriptor` error but does not hit this pointer being freed error

**Comment by jcrugzz** [comment]
ah yes makes sense why the file descriptor error is happening. But yea we shouldnt break if there is no start-log.

**Comment by jcrugzz** [comment]
yea im just retarded its fine. But @mmalecki I'm still seeing a 304 bytes leak coming from `env_copy` on OS X. Much better than before though.

image

Hmm I'm thinking that it might just not be smart enough to pick up on the reassignment [here](https://github.com/opsmezzo/forza/blob/mmalecki-fix-leaks/src/forza.c#L119) since it is added to the `uv_process_options_t options`. Because the logic for [freeing](https://github.com/opsmezzo/forza/blob/mmalecki-fix-leaks/src/forza.c#L151) it seems sane unless its some off by one error.

**Pull request merged**
